# @package _global_
# DiT-S on LIBERO-Plus with action text-CFG 1.5: 63.1.
defaults:
  - sim_libero_plus
  - override /task: libero_dits
  - _self_

ckpt: ./runs/libero_wm_rope_noattn_ind_mlp_latnorm_clip4int2_ratio4_32_2e-4/checkpoints/weights/step_173580.pt

EVALUATION:
  num_inference_steps: 4
  text_cfg_scale: 1.5
